### ISSUE TITLE
Describe`life_history_parameters`?

### ISSUE THREAD

**Issue by adarthau** [SFG-UCSB/fishery-manageR#9]
Section 5 describes how the The `life_history_parameters` data frame
`includes several important life history parameters that were found doing a literature review of this species. *L_infinity*, *k*, and *t0* describe the age-to-length relationship using the von Bertalanffy growth equation. *M* represents natural mortality. *Wa* and *Wb* describe the length-to-weight relationship.`

Will users know what *L_infinity*, *k*, *t0*, mean the von Bertalanffy growth equation? Will they be familiar with the von Bertalanffy growth equation?

**Comment by tclavelle** [comment]
The assumption is that users are familiar with parameters such as these that are common to fisheries analyses. The guide is meant to teach people who are already doing this type of analysis to do so using R rather than (gulp) Excel
